apiVersion: orchestrator.aiops.ibm.com/v1alpha1
kind: Installation
metadata:
  name: ibm-cp-watson-aiops
  namespace: {{ .Values.cpwaiops.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: “30”
spec:
  imagePullSecret: {{ .Values.cpwaiops.imagePullSecret }}
  license:
    accept: true
  pakModules:
  - name: aiopsFoundation
    enabled: true
  - name: applicationManager
    enabled: true
  - name: aiManager
    enabled: true
  - name: connection
    enabled: false
  size: small
  storageClass: {{ .Values.cpwaiops.storageClass }}
  storageClassLargeBlock: {{ .Values.cpwaiops.storageClassLargeBlock }}