apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-aiops-orchestrator
  namespace: {{ .Values.cpwaiops.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: “20”
spec:
  channel: {{ .Values.cpwaiops.channel }}
  installPlanApproval: Automatic
  name: ibm-aiops-orchestrator
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace



  